accelerator: ${general.device}
devices: 1
fast_dev_run: null
log_every_n_steps: 50
max_epochs: 3
overfit_batches: 0.0
precision: 16
logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: "/kaggle/working/logs/${general.project_name}/${general.unique_id}"
    # save_dir: "outputs/${general.project_name}/${general.unique_id}" # in sync with hydra output dir