# scheduler: "CosineAnnealingLR"  # Debug
# scheduler_kwargs:
#   T_max: ${trainer.max_epochs}
#   eta_min: 0.000001

scheduler: "OneCycleLR"
scheduler_kwargs:
  max_lr: 3e-4
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 1282