model_name: "resnet18"
pretrained: True
in_chans: 3
num_classes: ${general.num_classes}
global_pool: "avg"
# You typically want _self_ somewhere after the schema (base_config)
timm_kwargs:
  model_name: ${model.model_name}
  pretrained: ${model.pretrained}
  in_chans: ${model.in_chans}
  num_classes: ${model.num_classes}
  global_pool: ${model.global_pool}
  drop_rate: 0.5
  drop_path_rate: 0.4