defaults:
  - datamodule: base
  - model: rsna
  - criterion: base
  - optimizer: base
  - scheduler: base
  - metrics: base
  - stores: base
  - trainer: base
  # You typically want _self_ somewhere after the schema (base_config)
  - _self_

general:
  num_classes: 2
  device: "mps"
  project_name: "rsna"
  debug: False
  dataset_stage: "train"
  seed: 1992
  unique_id: ${now:%Y%m%d_%H%M%S} # in sync with hydra output dir
  output_dir: "outputs/${general.project_name}/${general.unique_id}" # in sync with hydra output dir
  # "/kaggle/working/logs/${general.project_name}/${general.unique_id}"
  monitor: "valid_multiclass_auroc"
  mode: "max"
  run_path: "examples.image_classification.rsna_breast_cancer_detection.run" # this is the path to each project's run script
  experiment_id: "exp_2_tf_efficientnetv2_s_gem_1024"
  experiment_df_path: "./data/rsna/experiments.csv"

hydra:
  run:
    dir: ${general.output_dir} # in sync with stores
