root_dir: !!python/object/apply:pathlib.Path ["./data/rsna"]
train_dir: !!python/object/apply:pathlib.Path ["./data/rsna/train"]
test_dir: !!python/object/apply:pathlib.Path ["./data/rsna/test"]
train_csv: !!python/object/apply:pathlib.Path ["./data/rsna/train/train.csv"]
test_csv: !!python/object/apply:pathlib.Path ["./data/rsna/test/test.csv"]
sub_csv: null
url: ""
blob_file: ""
image_extension: "png"
image_col_name: "patient_and_image_id"
image_path_col_name: "image_path"
target_col_name: "cancer"
group_by: "patient_id"
stratify_by: "stratify"
class_name_to_id:
  benign: 0
  malignant: 1