root_dir: !!python/object/apply:pathlib.Path ["./data/vegfru"]
train_dir: !!python/object/apply:pathlib.Path [""]
test_dir: !!python/object/apply:pathlib.Path [""]
train_csv: !!python/object/apply:pathlib.Path ["./data/vegfru/vegfru10.csv"]
test_csv: !!python/object/apply:pathlib.Path [""]
sub_csv: null
url: ""
blob_file: ""
image_extension: "png"
image_col_name: "image_id"
image_path_col_name: "image_path"
target_col_name: "class_id"
group_by: null
stratify_by: "class_id"


